language: generic
os:
  - linux
dist: trusty
sudo: false
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
      - ninja
      - clang-3.6
      - cmake
      
cache:
  apt: true
script:
  - export CC=/usr/bin/clang-3.6
  - export CXX=/usr/bin/clang++-3.6
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake .. -GNinja
  - ninja
  - find . -name "*" -exec echo "# {}" \; -exec cat "{}" \;
